### ISSUE TITLE
"no jvsthost2 in java.library.path" after running JVstHost.jar in CLI

### ISSUE THREAD

**Issue by malekinho8** [mhroth/jvsthost#10]
### Description

I am trying to use JVstHost to load and manipulate VST plugins on my Mac, but I am encountering an error when trying to run the JVstHost jar file. The error message is:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jvsthost2 in java.library.path: /Users/malek8/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
```

### Steps to reproduce

1.    Put the JVstHost.jar file into the Java classpath
2.    Put the libjvsthost2.jnilib file into /Library/Java/Extensions
3.    Run the command `java -jar JVstHost.jar /Library/Audio/Plug-Ins/VST/TAL-U-NO-LX-V2.vst`

### Expected behavior

The JVstHost should load and manipulate the VST plugin

### Actual behavior

I got the above error message.

### Additional information

1. I am using MacOS Monterrey 12.6
2. I am using Java version "19.0.2" 2023-01-17
3. I have tried to set the JAVA_OPTS environment variable to include the directory of the library, and also I tried to run the java command with the -D option to set the java.library.path.

Please let me know if you need any more information or if there is anything else I can try. I would really appreciate your help in resolving this issue, as I am interested in using this software for a passion project!

**Comment by klymenkor** [comment]
The same story =( Very sad. 
 
  I'm on macbook m2 processor.

  Seems like i got out of the real wold with this life-changing choice

**Comment by illettante** [comment]
Variation on the same theme. Windows 10 then Windows 11 PC, happens when running jar from command prompt, happens in IDE when running main class `com.synthbot.minihost.GuiMiniHost`:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.synthbot.audioplugin.vst.vst2.JVstHost2.loadPlugin(Ljava/lang/String;)J
        at com.synthbot.audioplugin.vst.vst2.JVstHost2.loadPlugin(Native Method)
        at com.synthbot.audioplugin.vst.vst2.JVstHost2.newInstance(JVstHost2.java:103)
        at com.synthbot.audioplugin.vst.vst2.JVstHost2.newInstance(JVstHost2.java:78)
        at com.synthbot.minihost.GuiMiniHost.<init>(GuiMiniHost.java:52)
        at com.synthbot.minihost.GuiMiniHost.main(GuiMiniHost.java:96)
```
I've tried 
- manually specifying the path at runtime with `java -Djava.library.path=`
- replacing `System.loadLibrary()` at line 147 of  JVstHost2.java with `SystemLoad()` and hardcoding the full filepath
but same error.
